---
title: "module_2_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(corrplot)
```

```{r}
getwd()
BodyFat = read.csv("BodyFat.csv")
# Observe dataset.
dim(BodyFat)
head(BodyFat)
tail(BodyFat)
summary(BodyFat)
```

## Correlation Matrix

```{r}
df_numeric = BodyFat[, -1] 

# Calculate the correlation matrix
cor_matrix = cor(df_numeric)

# Visualize the correlation matrix
corrplot(cor_matrix, method = "color", type = "upper", 
         tl.col = "black", tl.srt = 45, 
         col = colorRampPalette(c("blue", "white", "red"))(200),
         title = "Correlation Matrix")

# Considering the strong correlation between body fat and Abdomen as one of the 
# feature for the model
```

```{r}
# Assign dataset columns to easy-to-access vectors.
BODYFAT = BodyFat$BODYFAT
AGE = BodyFat$AGE
WEIGHT = BodyFat$WEIGHT
ADIPOSITY = BodyFat$ADIPOSITY

# Visualize histograms for body fat, age, weight, and adiposity.
m_1  = matrix(c(1,2,3,4), nrow = 2, ncol  =2, byrow = TRUE)
layout(m_1)
hist(BODYFAT,breaks=30, ylim = c(0, 40), cex.lab=1.5,cex.main=1.5,
     main="Histogram of Body Fat %",xlab="Body Fat %")
hist(AGE,breaks=30, ylim = c(0, 25), cex.lab=1.5,cex.main=1.5,
     main="Histogram of Age",xlab="Age (yrs)")
hist(WEIGHT,breaks=30, xlim = c(40, 160), cex.lab=1.5,cex.main=1.5,
     main="Histogram of Weight",xlab="Weight (kg)")
hist(ADIPOSITY,breaks=30, ylim  = c(0, 40), cex.lab=1.5,cex.main=1.5,
     main="Histogram of ADIPOSITY",xlab="ADIPOSITY(BMI)")
```


```{r}
ggplot(BodyFat, aes(y = BODYFAT)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 16, outlier.size = 2) +
  labs(title = "Boxplot for Body Fat", y = "Body Fat Percentage") +
  theme_minimal()
ggplot(BodyFat, aes(y = ADIPOSITY)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 16, outlier.size = 2) +
  labs(title = "Boxplot for Adiposity", y = "Adiposity") +
  theme_minimal()
ggplot(BodyFat, aes(y = ABDOMEN)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 16, outlier.size = 2) +
  labs(title = "Boxplot for Abdomen", y = "Abdomen") +
  theme_minimal()
```


```{r}
# robust method filter outlier
remove_outliers = function(data) {
  data = data[data$BODYFAT >= 3 & data$BODYFAT <= 60, ]
  data = data[data$ADIPOSITY >= 15 & data$ADIPOSITY <= 40, ]
  data = data[data$ABDOMEN >= 60 & data$ABDOMEN <= 140, ]
  
  return(data)
}

bodyfat_data = remove_outliers(BodyFat)
```

```{r}
cap_outliers = function(x) {
  Q1 = quantile(x, 0.25)
  Q3 = quantile(x, 0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR
  x[x < lower_bound] = lower_bound
  x[x > upper_bound] = upper_bound
  return(x)
}

bodyfat_data_v2 = BodyFat
df_numeric = BodyFat[sapply(BodyFat, is.numeric)]
df_capped = as.data.frame(lapply(df_numeric, cap_outliers))
bodyfat_data_v2[sapply(df, is.numeric)] = df_capped
bodyfat_data_v2 = remove_outliers(bodyfat_data_v2);
```


```{r}
# Build the linear regression model using ADIPOSITY, ABDOMEN, and AGE to predict BODYFAT
model = lm(BODYFAT ~ ADIPOSITY + ABDOMEN + AGE, data = bodyfat_data_v2)
summary(model)
```

```{r}

 predicted_values = predict(model, bodyfat_data)
      ggplot(bodyfat_data, aes(x = BODYFAT, y = predicted_values)) +
        geom_point(color = "blue") +
        geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
        labs(title = "Actual vs Predicted Body Fat", x = "Actual Body Fat (%)", y = "Predicted Body Fat (%)") +
        theme_minimal()
```

```{r}
 # Residual plot
residuals = model$residuals
ggplot(bodyfat_data_v2, aes(x = predict(model), y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Residual Plot", x = "Predicted Values", y = "Residuals") +
  theme_minimal()

```




```{r}
ggplot() +
  geom_histogram(aes(x = bodyfat_data_v2$BODYFAT), fill = "blue", alpha = 0.5, bins = 30) +
  geom_histogram(aes(x = predicted_values), fill = "green", alpha = 0.5, bins = 30) +
  labs(title = "Distribution of Actual vs Predicted Body Fat", x = "Body Fat (%)", y = "Count") +
  theme_minimal()
```


```{r}
ggplot(data = data.frame(residuals), aes(sample = residuals)) +
  stat_qq() +
  stat_qq_line() + 
  labs(title = "Q-Q Plot of Residuals for Body Fat Model",
       x = "Theoretical Quantiles",
       y = "Sample Quantiles") +
  theme_minimal()
```


```{r}
# Pii's value chart 
pii_BA = hatvalues(model)
par(mfrow = c(2,1))
n = dim(bodyfat_data)[1]
plot(1:n,pii_BA,type="p",pch=19,cex=1,cex.lab=1.5,
     xlab="Index (Each Observation)",ylab="Pii",main="Leverage Values (Pii for BodyFat and Adiposity)")

# Cook's distance chart 
cooki_BA = cooks.distance(model)
plot(1:n,cooki_BA,type="p",pch=19,cex=1,cex.lab=1.5,
     xlab="Index (Each Observation)",ylab="Cook's Distance",main="Influence Values (Cook's Distance for BodyFat and Adiposity)")
```







